apiVersion: v1
kind: ConfigMap
metadata:
  name:  {{ .Chart.Name }}-producer-env-configmap
  labels:
    app: {{ .Chart.Name }}
data:
  {{- toYaml .Values.env | nindent 2 }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Chart.Name }}-producer-properties-configmap
  labels:
    app: {{ .Chart.Name }}
data:
{{- if not .Values.config.custom }}
{{ (tpl (.Files.Glob "config/*").AsConfig . ) | indent 2 }}
{{- else }}
  producer.properties: |
{{ .Values.config.custom | indent 4}}
{{- end }}