{{- if .Values.tls }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Chart.Name }}-pki-secret
data:
  ca.crt:
{{ .Values.tls.ca | b64enc | indent 4 }}
  tls.crt:
{{ .Values.tls.cert | b64enc | indent 4 }}
  tls.key:
{{ .Values.tls.key | b64enc | indent 4 }}
{{- end }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Chart.Name }}-client-secret
data:
  ca.crt:
{{ .Values.client.ca | b64enc | indent 4 }}
  tls.crt:
{{ .Values.client.cert | b64enc | indent 4 }}
  tls.key:
{{ .Values.client.key | b64enc | indent 4 }}